server {
    listen 80;
    listen [::]:80;
    server_name 149.28.118.25;

    # TheStudy - root
    location / {
        root /var/www/thestudy;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Repeatly - at /repeatly/
    location /repeatly/ {
        alias /var/www/repeatly/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Regreta - at /regreta/
    location /regreta/ {
        alias /var/www/regreta/;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
